# Generated by Django 3.2.9 on 2021-11-13 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_tables4_tables5'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tables5',
        ),
    ]
